substitutions:
  name: "m5-dial"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password  

packages:
  m5_tough_package:
    url: https://github.com/SmartHome-yourself/m5-dial-for-esphome
    ref: main
    file: shys-m5-dial.yaml
    refresh: 1s

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Berlin
    
shys_m5_dial:
  name: Dial
  time_component: homeassistant_time
  screen_off_time: 45000
  screensaver: clock
  rotary_step_width: 5
  long_press_duration: 1200
  font: default
  font_factor: 1

  display_rotate: 2
  

  devices:
    lights:
      - entity: light.DEIN_RGBWW_LIGHT
        name: "RGBWW Light"
        modes:
          white_mode: 
            enable: true
            rotary_step_width: 100          
          rgb_mode:
            enable: true
            rotary_step_width: 30
          dimm_mode:
            enable: true
            rotary_step_width: 10
      - entity: light.DEIN_RGB_LICHT
        name: "RGB Light"
        modes:
          dimm_mode:
            enable: true
            rotary_step_width: 10
          rgb_mode: 
            enable: true
            rotary_step_width: 30
      - entity: light.DEIN_DIMMBARES_LICHT
        name: "Dimmable"
        modes:
          dimm_mode:
            enable: true
      - entity: light.DEIN_DIMM_WEISS_LICHT
        name: "Tunable White"
        modes:
          dimm_mode:
            enable: true
          white_mode: 
            enable: true
            rotary_step_width: 100
        
    climates:
      - entity: climate.DEINE_HEIZUNG
        name: Buro
        modes:
          temp_mode:
            min_temperature: 4
            max_temperature: 30
    
    covers:
      - entity: cover.DEIN_COVER
        name: Gardiene
        modes:
          position_mode:
            rotary_step_width: 5

    switches:
      - entity: switch.DEIN_SCHALTER
        name: Buro Licht

    fans:
      - entity: fan.DEIN_VENTILATOR
        name: Ventilator
        modes:
          speed_mode:
            changeable_direction: true
            rotary_step_width: 10


    media_player:
      - entity: media_player.DEIN_AMAZON_ECHO
        name: Amazon Echo
        modes:
          play_mode:
            rotary_step_width: 10
          source_mode:
            rotary_step_width: 1
            sources:
              - name: 1Live
                content_id: 1Live
                content_type: TUNEIN
              - name: WDR2
                content_id: WDR 2 Rheinland
                content_type: TUNEIN
              - name: SunShine Live
                content_id: SUNSHINE LIVE
                content_type: TUNEIN
              - name: SunShine House
                content_id: SUNSHINE LIVE - House
                content_type: TUNEIN

      - entity: media_player.DEIN_DLNA_PLAYER
        name: Radio
        modes:
          play_mode:
            rotary_step_width: 10
          source_mode:
            rotary_step_width: 1
            sources:
              - name: 1Live
                content_id: "https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3"
                content_type: custom
              - name: WDR2
                content_id: "http://wdr-wdr2-bergischesland.icecast.wdr.de/wdr/wdr2/bergischesland/mp3/128/stream.mp3"
                content_type: custom
              - name: Sun Shine Live
                content_id: "http://sunshinelive.hoerradar.de/sunshinelive-live-mp3-hq"
                content_type: custom
              - name: Sun Shine House
                content_id: "http://sunshinelive.hoerradar.de/sunshinelive-house-mp3-hq"
                content_type: custom

    lock:
      - entity: lock.DEIN_SMARTLOCK
        name: Haustür
        modes:
          lock_mode:
            rotary_step_width: 1
            open_on_button: true