substitutions:
  effectCount: "9"

esphome:
  name: shys-rgbw-smd-4-einzelkanal
  friendly_name: 4 Einzelkanal Controller

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "RGB SMD"
    password: "12345678"
  
captive_portal:

logger:
  hardware_uart: UART1
api:
  encryption:
    key: !secret ESPHOME_ENCRYPTION_KEY

ota:
  platform: esphome
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    name: "Mode Button"
    pin: GPIO4
    id: mode_button
    on_press:
      then:
        if:
          condition:
            light.is_on: panel_left
          then:
            - light.turn_off: panel_left
            - light.turn_off: panel_right
            - light.turn_off: spotlight          
          else:
            - light.turn_on: panel_left
            - light.turn_on: panel_right
            - light.turn_on: spotlight

output:
   - platform: esp8266_pwm
     id: white_out
     pin: GPIO5
     max_power: 0.5
   - platform: esp8266_pwm
     id: green_out
     pin: GPIO12
     max_power: 0.5
   - platform: esp8266_pwm
     id: red_out
     pin: GPIO14

#   - platform: esp8266_pwm
#     id: blue_out
#     pin: GPIO13

light:
  - platform: monochromatic
    name: "Stream Panel rechts"
    output: white_out
    id: panel_right

  - platform: monochromatic
    name: "Stream Panel links"
    output: green_out
    id: panel_left

  - platform: monochromatic
    name: "Spotlight LED Monitor"
    output: red_out
    id: spotlight

  - platform: neopixelbus
    type: BRG
    variant: WS2812
    pin: TX #GPIO13
    num_leds: 12
    name: "RGB-LED Backlight Büro Daniel"
    id: rgb_lde_backlight_daniel_buro
    
