substitutions:
  name: atom-bluetooth-proxy-e9d548
  friendly_name: Bluetooth Proxy e9d548

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
ota:
  platform: esphome
  
logger:

api:
  encryption:
    key: UVxrl1pIIW/G7kaLkyOiK89U7lJeRBMFj+HUppOkdto=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .fritz.box

esp32_ble_tracker:
    scan_parameters:
        interval: 1100ms
        window: 1100ms

bluetooth_proxy:
   active: true