blank_issues_enabled: true
contact_links:
  - name: 💬 Diskussionen & Fragen
    url: https://github.com/SmartHome-yourself/shys-collection/discussions
    about: Für allgemeine Fragen und Diskussionen nutze bitte die Discussions

