name: Node-RED Flow Submission
description: Submit Node-RED flows for the community collection
title: "Hier dein Projekt-Name"
labels: ["nodered", "flow"]
body:
  - type: textarea
    id: description
    attributes:
      label: "ZIP-Datei hochladen"
      description: "Ziehe deine ZIP-Datei hier hinein oder füge sie als Anhang hinzu"
      placeholder: "ZIP-Datei hier hineinziehen oder als Anhang hinzufügen..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📁 ZIP-Upload
        
        **Wichtig:** Lade dein Projekt als ZIP-Datei hoch, damit es automatisch verarbeitet werden kann.
        
        1. Erstelle dein Projekt basierend auf dem Skeleton aus `/skeletons/nodered-template/`
        2. Packe den kompletten Projektordner als ZIP
        3. Ziehe die **ZIP-Datei** unten in das Textfeld hinein
        4. Die README.md in der ZIP wird automatisch verwendet

  - type: dropdown
    id: project_type
    attributes:
      label: "Project Type"
      options:
        - "nodered"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📁 Erwartete Ordnerstruktur
        ```
        templates/nodered/flows/<slug>/
        ├── README.md
        ├── flow.json
        └── (weitere Flow-Dateien)
        ```

  - type: checkboxes
    id: checklist
    attributes:
      label: "Prüfung abgeschlossen"
      description: "Ich bestätige, dass ich alles korrekt vorbereitet habe"
      options:
        - label: "✅ Ich habe das Skeleton zur Erstellung der ZIP-Datei verwendet, 
                  alle Dateien korrekt benannt, die README.md gefüllt,
                  meinen Flow getestet und alle Ordner-/Dateinamen sind in kebab-case"
          required: true

